# Generated by Django 5.2.11 on 2026-05-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Salat nomi')),
                ('price', models.CharField(max_length=50, verbose_name='Narxi')),
                ('description', models.TextField(verbose_name="Tarkibi va ma'lumot")),
                ('image_url', models.URLField(max_length=500, verbose_name='Rasm linki')),
            ],
        ),
        migrations.CreateModel(
            name='Shashlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Shashlik nomi')),
                ('price', models.CharField(max_length=50, verbose_name='Narxi')),
                ('description', models.TextField(verbose_name="Tarkibi va ma'lumot")),
                ('image_url', models.URLField(max_length=500, verbose_name='Rasm linki')),
            ],
        ),
        migrations.CreateModel(
            name='YaxnaIchimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ichimlik nomi')),
                ('price', models.CharField(max_length=50, verbose_name='Narxi')),
                ('description', models.TextField(verbose_name="Ma'lumot")),
                ('image_url', models.URLField(max_length=500, verbose_name='Rasm linki')),
            ],
        ),
    ]
